# -*- coding: utf-8 -*-
"""arreglobidimencional.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X0S__vS91DMVb22NQCFKM3-mI2TrWWOC
"""

#Se establece el tamaño del arreglo
m=int(input("Ingresa el número de filas: ")) #Filas
n=int(input("Ingresa el número de columnas: ")) #Columnas

#Se crea el arreglo
A=[]

#Se crea una variable para establecer si es de Netflix o de Disney + que inicia vacía
valor=""

#Se inicializa el arreglo, es un proceso necesario para los arreglos bidimensionales
for i in range(m):
  A.append([0]*n)

#Inicia el proceso de llenado del arreglo bidimensional
for i in range (m):

  #Este if es auxiliar solamente para mostrar Netflix o Disney + en la captura
  if (i==0):
    valor="Netflix"
  else:
    valor="Disney +"

  for j in range (n):
    #Así se llena el arreglo bidimensional
    A[i][j]=input("Introduzca la serie "+str(j+1)+" de "+valor+": ")

#Se imprime el arreglo bidimensional
print(A)