# -*- coding: utf-8 -*-
"""Copia de Gato_Examen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ttuXF58DAqH32sz9j83nf3I_AbcLl8VZ
"""

print("a1|a2|a3")
print("--------")
print("a4|a5|a6")
print("--------")
print("a7|a8|a9")
a1=0
a2=0
a3=0
a4=0
a5=0
a6=0
a7=0
a8=0
a9=0

jx=input('Jugador X Ingresa la casilla: ')
if(jx=='a1'):
  a1=1
elif(jx=='a2'):
  a2=1
elif(jx=='a3'):
  a3=1
elif(jx=='a4'):
  a4=1
elif(jx=='a5'):
  a5=1
elif(jx=='a6'):
  a6=1
elif(jx=='a7'):
  a7=1
elif(jx=='a8'):
  a8=1
elif(jx=='a9'):
  a9=1

jo=input('Jugador O Ingresa la casilla: ')
if(jo=='a1'):
  a1=2
elif(jo=='a2'):
  a2=2
elif(jo=='a3'):
  a3=2
elif(jo=='a4'):
  a4=2
elif(jo=='a5'):
  a5=2
elif(jo=='a6'):
  a6=2
elif(jo=='a7'):
  a7=2
elif(jo=='a8'):
  a8=2
elif(jo=='a9'):
  a9=2

jx=input('Jugador X Ingresa la casilla: ')
if(jx=='a1'):
  a1=1
elif(jx=='a2'):
  a2=1
elif(jx=='a3'):
  a3=1
elif(jx=='a4'):
  a4=1
elif(jx=='a5'):
  a5=1
elif(jx=='a6'):
  a6=1
elif(jx=='a7'):
  a7=1
elif(jx=='a8'):
  a8=1
elif(jx=='a9'):
  a9=1

jo=input('Jugador O Ingresa la casilla: ')
if(jo=='a1'):
  a1=2
elif(jo=='a2'):
  a2=2
elif(jo=='a3'):
  a3=2
elif(jo=='a4'):
  a4=2
elif(jo=='a5'):
  a5=2
elif(jo=='a6'):
  a6=2
elif(jo=='a7'):
  a7=2
elif(jo=='a8'):
  a8=2
elif(jo=='a9'):
  a9=2

jx=input('Jugador X Ingresa la casilla: ')
if(jx=='a1'):
  a1=1
elif(jx=='a2'):
  a2=1
elif(jx=='a3'):
  a3=1
elif(jx=='a4'):
  a4=1
elif(jx=='a5'):
  a5=1
elif(jx=='a6'):
  a6=1
elif(jx=='a7'):
  a7=1
elif(jx=='a8'):
  a8=1
elif(jx=='a9'):
  a9=1

if((a1==1) and (a5==1) and (a9==1)):
  print('--Gana jugador x--')
elif((a1==1) and (a4==1) and (a7==1)):
  print('--Gana jugador x--')
elif((a4==1) and (a5==1) and (a6==1)):
  print('--Gana jugador x--')
elif((a3==1) and (a5==1) and (a7==1)):
  print('--Gana jugador x--')
elif((a7==1) and (a8==1) and (a9==1)):
  print('--Gana jugador x--')
elif((a2==1) and (a5==1) and (a8==1)):
  print('--Gana jugador x--')
elif((a3==1) and (a6==1) and (a9==1)):
  print('--Gana jugador x--')
if((a1==1) and (a2==1) and (a3==1)):
  print('--Gana jugador x--')

jo=input('Jugador O Ingresa la casilla: ')
if(jo=='a1'):
  a1=2
elif(jo=='a2'):
  a2=2
elif(jo=='a3'):
  a3=2
elif(jo=='a4'):
  a4=2
elif(jo=='a5'):
  a5=2
elif(jo=='a6'):
  a6=2
elif(jo=='a7'):
  a7=2
elif(jo=='a8'):
  a8=2
elif(jo=='a9'):
  a9=2

if((a1==2) and (a2==2) and (a3==2)):
  print('--Gana jugador o--')
elif((a1==2) and (a5==2) and (a9==2)):
  print('--Gana jugador o--')
elif((a1==2) and (a4==2) and (a7==2)):
  print('--Gana jugador o--')
elif((a4==2) and (a5==2) and (a6==2)):
  print('--Gana jugador o--')
elif((a3==2) and (a5==2) and (a7==2)):
  print('--Gana jugador o--')
elif((a7==2) and (a8==2) and (a9==2)):
  print('--Gana jugador o--')
elif((a2==2) and (a5==2) and (a8==2)):
  print('--Gana jugador o--')
elif((a3==2) and (a6==2) and (a9==2)):
  print('--Gana jugador x--')

jx=input('Jugador X Ingresa la casilla: ')
if(jx=='a1'):
  a1=1
elif(jx=='a2'):
  a2=1
elif(jx=='a3'):
  a3=1
elif(jx=='a4'):
  a4=1
elif(jx=='a5'):
  a5=1
elif(jx=='a6'):
  a6=1
elif(jx=='a7'):
  a7=1
elif(jx=='a8'):
  a8=1
elif(jx=='a9'):
  a9=1

if((a1==1) and (a2==1) and (a3==1)):
  print('--Gana jugador x--')
elif((a1==1) and (a5==1) and (a9==1)):
  print('--Gana jugador x--')
elif((a1==1) and (a4==1) and (a7==1)):
  print('--Gana jugador x--')
elif((a4==1) and (a5==1) and (a6==1)):
  print('--Gana jugador x--')
elif((a3==1) and (a5==1) and (a7==1)):
  print('--Gana jugador x--')
elif((a7==1) and (a8==1) and (a9==1)):
  print('--Gana jugador x--')
elif((a2==1) and (a5==1) and (a8==1)):
  print('--Gana jugador x--')
elif((a3==1) and (a6==1) and (a9==1)):
  print('--Gana jugador x--')

jo=input('Jugador O Ingresa la casilla: ')
if(jo=='a1'):
  a1=2
elif(jo=='a2'):
  a2=2
elif(jo=='a3'):
  a3=2
elif(jo=='a4'):
  a4=2
elif(jo=='a5'):
  a5=2
elif(jo=='a6'):
  a6=2
elif(jo=='a7'):
  a7=2
elif(jo=='a8'):
  a8=2
elif(jo=='a9'):
  a9=2

if((a1==2) and (a2==2) and (a3==2)):
  print('--Gana jugador o--')
elif((a1==2) and (a5==2) and (a9==2)):
  print('--Gana jugador o--')
elif((a1==2) and (a4==2) and (a7==2)):
  print('--Gana jugador o--')
elif((a4==2) and (a5==2) and (a6==2)):
  print('--Gana jugador o--')
elif((a3==2) and (a5==2) and (a7==2)):
  print('--Gana jugador o--')
elif((a7==2) and (a8==2) and (a9==2)):
  print('--Gana jugador o--')
elif((a2==2) and (a5==2) and (a8==2)):
  print('--Gana jugador o--')
elif((a3==2) and (a6==2) and (a9==2)):
  print('--Gana jugador x--')

jx=input('Jugador X Ingresa la casilla: ')
if(jx=='a1'):
  a1=1
elif(jx=='a2'):
  a2=1
elif(jx=='a3'):
  a3=1
elif(jx=='a4'):
  a4=1
elif(jx=='a5'):
  a5=1
elif(jx=='a6'):
  a6=1
elif(jx=='a7'):
  a7=1
elif(jx=='a8'):
  a8=1
elif(jx=='a9'):
  a9=1

if((a1==1) and (a2==1) and (a3==1)):
  print('--Gana jugador x--')
elif((a1==1) and (a5==1) and (a9==1)):
  print('--Gana jugador x--')
elif((a1==1) and (a4==1) and (a7==1)):
  print('--Gana jugador x--')
elif((a4==1) and (a5==1) and (a6==1)):
  print('--Gana jugador x--')
elif((a3==1) and (a5==1) and (a7==1)):
  print('--Gana jugador x--')
elif((a7==1) and (a8==1) and (a9==1)):
  print('--Gana jugador x--')
elif((a2==1) and (a5==1) and (a8==1)):
  print('--Gana jugador x--')
elif((a3==1) and (a6==1) and (a9==1)):
  print('--Gana jugador x--')
else:
  print("Empate")