# -*- coding: utf-8 -*-
"""hombres/mujeres promedio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c6rcI6LZGKW1vRAKxn7cJCyS3jRCmr3X
"""

jm=(int(input("cuantas categorias?: ")))
a=(int(input("cuantos alumnos?: ")))

M="[i][j]"
H="[i][j]"
suma=""
prom=""
A=[]
valor=""
for i in range(a):
  A.append([0]*jm)
for i in range(a):
  for j in range(jm):
    if (j==0):
      valor="numero de control"
    elif(j==1):
      valor="nombre del alumno"
    elif(j==2):
      valor="calificacion"
    elif(j==3):
      valor="genero M/H"
    A[i][j]=input("ingresa su "+valor+ ":" )
print(A)
Totalh=0 
Totalm=0
Calho=0
Calmu=0
Promediomuj=0
Promediohom=0
for i in range(0,a):
  if(A[i][3]=='H'):
    Totalh=Totalh+1
    Calho=Calho+int(A[i][2])
  if(A[i][3]=='M'):
    Totalm=Totalm+1
    Calmu=Calmu+int(A[i][2])

Promediohom=Calho/Totalh
Promediomuj=Calmu/Totalm
print("promedio de mujeres: ", Promediomuj) 
print("promedio de hombres: ", Promediohom)