# -*- coding: utf-8 -*-
"""piedra, papel y tijera

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n8m4dpED3Kczmpjksh4EvhHeorE02Ec6
"""

#1. piedra
#2. papel
#3. tijera
jugador1=int(input("jugador 1 ingresa tu opcion "))
jugador2=int(input("jugador 2 ingresa tu opcion "))
if((jugador1==1)and(jugador2==2)):
  print ("gano jugador 2")
elif((jugador1==1)and(jugador2==3)):
  print ("gano el jugador 1")
elif((jugador1==1)and(jugador2==1)): 
  print ("empate")
elif((jugador1==3)and(jugador2==1)):
  print("ganó jugador 2")
elif((jugador1==3)and(jugador2==2)):
  print("ganó jugador 1")
elif((jugador1==3)and(jugador2==3)):
  print("empate")