# -*- coding: utf-8 -*-
"""practica1401.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OlUDTcbWFr6eVhD3s0EBL_kfS0jESzWj
"""

n1=int(input("ingresa el primer numero ")) 
n2=int(input("ingresa el segundo numero "))
sum=n1+n2
print("el resultado es", sum)

calif=float(input("ingresa la calificacion "))
if(calif<7):
  print("reprobado ")
else:
  print("aprobado ")

#1. piedra
#2. papel
#3. tijera
jugador1=int(input("jugador 1 ingresa tu opcion "))
jugador2=int(input("jugador 2 ingresa tu opcion "))
if((jugador1==1)and(jugador2==2)):
  print ("gano jugador 2")
elif((jugador1==1)and(jugador2==3)):
  print ("gano el jugador 1")
elif((jugador1==1)and(jugador2==1)) 
  print ("empate")
elif((jugador1==3)and(jugador2==1)):
  print("ganó jugador 2")
elif((jugador1==3)and(jugador2==2)):
  print("ganó jugador 1")
elif((jugador1==3)and(jugador2==3)):
  print("empate")