# -*- coding: utf-8 -*-
"""programas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14hj52tmmnm5FkjqhhLWom8ngggfvWUoU
"""

Alumnosfavoritos=['Karina', 'Mane', 'El cholo', 'Macuarro', 'Greñas', 'Carlangas', 'Chuchin']
print(Alumnosfavoritos[3])

Calificaciones=[8,10,9,5,7,4,1]
print(Calificaciones[4])

prueba=[]
prueba.append(int(input("ingresa un numero ")))
print(prueba[0])



prueba=[]
prueba.append(int(input("ingresa un numero ")))
prueba.append(int(input("ingresa un numero ")))
prueba.append(int(input("ingresa un numero ")))
prueba.append(int(input("ingresa un numero ")))
prueba.append(int(input("ingresa un numero ")))
prueba.append(int(input("ingresa un numero ")))
prueba.append(int(input("ingresa un numero ")))
prueba.append(int(input("ingresa un numero ")))
prueba.append(int(input("ingresa un numero ")))
print(prueba[1])
print(prueba[3])



numeros=[]
for i in range (0,5):
  numeros.append(int(input('Ingresa el numero: ')))
print(numeros[0])
print(numeros[3])