# -*- coding: utf-8 -*-
"""tabla de multiplicar con arreglos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pn7TEl82xUNG8Pe86tecBUzKM3S0VGMp
"""



arr=[]
chochito=(int(input("ingresa el numero para la tabla: ")))
for i in range (0,10):
  mul=chochito*(i+1)
  arr.append(mul)
  
  print(mul, arr[i])