# -*- coding: utf-8 -*-
"""tablas de multiplicar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvjBwcch6PISCU_leacQCsgv_YWkfeZi
"""



r=0
M= int(input("que tabla deseas consultar"))
for i in range (0,11):
  r= M*i 
  print(M, 'x', i, '=', r)